[package]
name = "BrainFk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
colored = "2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

